[package]
name = "userfaultfd"
version = "0.1.0"
authors = ["Adam C. Foltzer <acfoltzer@fastly.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
libc = "0.2.65"
nix = "0.13"
thiserror = "1.0.4"
userfaultfd-sys = { path = "userfaultfd-sys" }
