[package]
name = "linux-version"
version = "0.1.0"
authors = ["Adam C. Foltzer <acfoltzer@fastly.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
nix = "0.13"
semver = "0.9"

[build-dependencies]
bindgen = "0.47"