[package]
name = "userfaultfd-sys"
version = "0.1.0"
authors = ["Adam C. Foltzer <acfoltzer@fastly.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Low-level bindings for userfaultfd functionality on Linux."

build = "build.rs"

[dependencies]
cfg-if = "0.1"

[build-dependencies]
bindgen = "0.51"
cc = "1.0"
linux-version = { version = "=0.1.0", path = "../linux-version" }
